version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Devcontainer_dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:blob

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # # Commented out as we don't need it yet
  # db:
  # # Below creates an MS SQL Server inside the Codespaces environment
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   restart: unless-stopped
  #   environment:
  #     ACCEPT_EULA: Y
  #     MSSQL_SA_PASSWORD: mssqlpassword
  #   ports:
  #     - 1433:1433
  #   # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
  #   # (Adding the "ports" property to this file will not forward from a Codespace.)

  # blob:
  # # Below creates a temporary blob storage server within the Codespace
  #   image: mcr.microsoft.com/azure-storage/azurite:latest
  #   restart: unless-stopped
  #   environment:
  #     SOMETHING: blahblah
  #   ports:
  #     - 10000:10000
  #     - 10001:10001
  #     - 10002:10002
  #   # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
  #   # (Adding the "ports" property to this file will not forward from a Codespace.)
    